/**
 * Next.js middleware for Gibson Dashboard.
 *
 * Wraps Auth.js v5's `auth` middleware with active-tenant routing:
 *
 *   - Unauthenticated → DENIED unless the path is on the public allowlist
 *     (`PUBLIC_PATHS` / `PUBLIC_PREFIXES` below). Navigations get 302 `/login`
 *     with a `callbackUrl`; `/api/**` gets `401 {"error":"unauthenticated"}`.
 *     This is an explicit decision taken here, NOT Auth.js's default, which
 *     does not apply to the `auth(handler)` wrapper form this file uses.
 *   - Authenticated, no `gibson_active_tenant` cookie → 302 `/select-tenant`.
 *   - Authenticated, cookie present but tampered/HMAC-invalid → 302 `/select-tenant`
 *     (no error surfaced; identical UX to "haven't picked yet").
 *   - Authenticated, cookie names a tenant the user is no longer a member of →
 *     clear cookie, 302 `/select-tenant`.
 *   - Authenticated, FGA / daemon unreachable when validating membership →
 *     302 `/login/error?reason=<machine-readable>` (deterministic error page,
 *     never federated-signout).
 *   - Authenticated with valid membership → forward to the route handler.
 *
 * The federated-signout-on-tenantless-session rule from the pre-spec
 * implementation is GONE. "No tenant" is now a product state (onboarding /
 * picker), not a broken-session sentinel.
 */

import { NextResponse, type NextRequest } from "next/server";
import { auth } from "@/auth";
import { readRawActiveTenant, ACTIVE_TENANT_COOKIE_NAME } from "@/src/lib/auth/active-tenant";
import {
  getMyMemberships,
  MembershipResolutionError,
} from "@/src/lib/auth/membership";
import { membershipReasonToLoginErrorReason } from "@/src/lib/auth/login-error-mapping";
import { decideHostSplit, loadHostSplitConfig } from "@/src/lib/host-routing";
import { CORRELATION_HEADER, generateCorrelationId } from "@/src/lib/auth/correlation";
import { popLastFiredSubsystem } from "@/src/lib/test-fixtures/fault-injection";
import { ensureCsrfCookie } from "@/src/lib/csrf";
import { logger } from "@/src/lib/logger";

// Pin middleware to the Node.js runtime: membership.ts → gibson-client.ts
// transitively pulls in @grpc/grpc-js (via the SPIFFE Workload-API client),
// which uses Node-only modules (`dns`, `fs`, `cluster`). Edge Runtime cannot
// host those, and Next.js 16's default of Edge Runtime for middleware would
// fail the build at module-graph trace time.
export const runtime = "nodejs";

const PROTECTED_PREFIX = "/dashboard";

// ---------------------------------------------------------------------------
// Deny-by-default access model.
//
// Before this, an unauthenticated request fell through with
// `NextResponse.next()` on the belief that "Auth.js redirects to /login via its
// default behavior". It does not: that default only applies when middleware is
// the bare `auth` export, and this file uses the wrapper form
// `export default auth(async (req) => ...)`, which hands the decision entirely
// to this function. The `authorized` callback in auth.ts was dead for the same
// reason and has been deleted rather than left standing as decorative
// protection.
//
// The model now is: a request is DENIED unless its path is on one of the
// allowlists below. Adding a route does not silently make it public.
// ---------------------------------------------------------------------------

/** Paths served to anonymous callers. Exact matches. */
const PUBLIC_PATHS: ReadonlySet<string> = new Set([
  // Front door. Self-hosted: the login page (ADR-0006). SaaS: the host split
  // above has already redirected app.<domain>/ to /dashboard.
  "/",
  "/login",
  "/signin",
  "/signup",
  "/forgot-password",
  "/reset-password",
  "/verify-email",
  // Design-token reference page under app/(public).
  "/design-tokens",
  // Crawler + browser well-knowns generated by app/robots.ts, app/sitemap.ts
  // and the icon route handlers.
  "/robots.txt",
  "/sitemap.xml",
  "/manifest.webmanifest",
  "/favicon.ico",
  "/icon.png",
  "/apple-icon.png",
]);

/** Public path PREFIXES. A trailing segment is matched, `/login/error` etc. */
const PUBLIC_PREFIXES: readonly string[] = [
  "/login/",
  "/signin/",
  "/signup/",
  "/verify-email/",
  // Invite acceptance is authenticated by the opaque token in the URL, not by
  // a session, the invitee has no account yet.
  "/invite/",
  "/.well-known/",
  // Bundled assets. `_next/static` and `_next/image` are already excluded by
  // the matcher; this covers the remaining `_next` surface (dev HMR endpoints).
  "/_next/",
  // Auth.js OIDC callbacks. Matcher-excluded already; listed so the allowlist
  // reads as the complete public surface rather than half of it.
  "/api/auth/",
  // Kubernetes probes. No session, by definition.
  "/api/health",
  // Signup polling. Guarded by an opaque per-signup capability, not a session.
  "/api/signup/",
  // Prometheus scrape target. Guarded by DASHBOARD_METRICS_ALLOWED_CIDRS in the
  // route handler; a scraper has no session and must not be redirected to /login.
  "/api/metrics",
  // Explicitly-public config projection consumed by the anonymous login/signup
  // pages (app/api/config/public).
  "/api/config/public",
  // Public status endpoint. Its handler owns its own rate limiting and
  // validation. contact-sales is NOT here: www owns lead capture on its own
  // CloudFront origin (ADR-0009), and an unauthenticated POST that emails a
  // fixed inbox has no place in a customer's self-hosted cluster.
  "/api/status",
];

/**
 * Authenticated but deliberately TENANT-EXEMPT prefixes.
 *
 * A user in the zero-membership onboarding state has no tenant by definition,
 * so the onboarding endpoints the onboarding page calls cannot be gated on
 * having one. Everything else under `/api` gets the full membership + active
 * tenant check.
 */
const TENANT_EXEMPT_PREFIXES: readonly string[] = ["/api/onboarding"];

function isPublicPath(pathname: string): boolean {
  if (PUBLIC_PATHS.has(pathname)) return true;
  return PUBLIC_PREFIXES.some((p) => pathname.startsWith(p));
}

/** API requests get machine-readable JSON, never an HTML redirect. */
function isApiPath(pathname: string): boolean {
  return pathname === "/api" || pathname.startsWith("/api/");
}

/**
 * Paths requiring a resolved tenant + current membership.
 *
 * Previously only `/dashboard`, which left every `/api/**` route relying solely
 * on its own handler-level authz. The middleware check is defence in depth in
 * front of that, not a replacement for it.
 */
function requiresTenant(pathname: string): boolean {
  if (TENANT_EXEMPT_PREFIXES.some((p) => pathname.startsWith(p))) return false;
  return pathname.startsWith(PROTECTED_PREFIX) || isApiPath(pathname);
}

/** 401 for API callers, 302 to the login page for navigations. */
function denyUnauthenticated(
  req: NextRequest,
  pathname: string,
  search: string,
): NextResponse {
  if (isApiPath(pathname)) {
    return NextResponse.json(
      { error: "unauthenticated", reason: "no_session" },
      { status: 401 },
    );
  }
  const url = new URL("/login", req.nextUrl.origin);
  url.searchParams.set("callbackUrl", pathname + (search || ""));
  return NextResponse.redirect(url);
}

// Host split (deploy#630 S11). Computed once at module load, origins are
// fixed for the pod's lifetime. Null in single-origin dev (no WWW_URL).
const HOST_SPLIT = loadHostSplitConfig();

export default auth(async (req) => {
  const { pathname, search } = req.nextUrl;

  // 0. www/app host split. Runs before auth so marketing pages (www) never
  //    touch tenant resolution, and the product host (app) never serves the
  //    public landing. Cross-host requests 307 to the canonical host; app "/"
  //    goes to /dashboard. See src/lib/host-routing.ts.
  if (HOST_SPLIT) {
    const decision = decideHostSplit(
      req.headers.get("host") ?? "",
      pathname,
      search ?? "",
      HOST_SPLIT,
    );
    if (decision.kind === "redirect") {
      return NextResponse.redirect(new URL(decision.url, req.nextUrl.origin), {
        status: 307,
      });
    }
  }

  const session = req.auth;

  // Spec auth-resolution-hardening R2.5/R3.5, every request through
  // middleware carries a correlation ID. Generate one if absent so all
  // downstream Server Components / route handlers / log lines can
  // correlate against the same request.
  let correlationId = req.headers.get(CORRELATION_HEADER);
  if (!correlationId) {
    correlationId = generateCorrelationId();
  }
  const reqHeaders = new Headers(req.headers);
  reqHeaders.set(CORRELATION_HEADER, correlationId);

  // 1a. Auth.js error redirect, when the jwt or signIn callback throws, Auth.js
  //     redirects to pages.error (/login) with ?error=Callback or ?error=<name>.
  //     Intercept those and reroute to /login/error?reason=<machine-readable>
  //     so the user sees a deterministic error page rather than the login form
  //     with an error query param that the form doesn't surface. This covers
  //     the fault-injection paths for "token-exchange" and "jwks" faults.
  if (pathname === "/login") {
    const authError = req.nextUrl.searchParams.get("error");
    if (authError) {
      // Map Auth.js error names to our LoginErrorReason codes.
      let reason: string;
      if (authError === "Callback") {
        // jwt callback threw, could be token-exchange or jwks fault.
        // popLastFiredSubsystem() returns which fault subsystem last fired,
        // letting us pick the right reason code. Falls back to
        // oidc_token_exchange_failed for non-fixture causes.
        const lastFired = popLastFiredSubsystem();
        if (lastFired === "jwks") {
          reason = "jwks_unavailable";
        } else {
          reason = "oidc_token_exchange_failed";
        }
      } else if (authError === "OAuthCallbackError") {
        reason = "oidc_token_exchange_failed";
      } else if (authError === "JWTSessionError") {
        reason = "session_invalid";
      } else {
        reason = "oidc_token_exchange_failed";
      }
      const url = new URL("/login/error", req.nextUrl.origin);
      url.searchParams.set("reason", reason);
      if (correlationId) url.searchParams.set("correlationId", correlationId);
      return NextResponse.redirect(url);
    }
  }

  // 1. Unauthenticated requests: DENY unless the path is on the public
  //    allowlist. This used to be an unconditional `NextResponse.next()`,
  //    i.e. the middleware forwarded anonymous traffic to protected route
  //    handlers and relied on each of them to re-derive the same decision.
  if (!session?.user) {
    if (!isPublicPath(pathname)) {
      logger.warn(
        {
          scope: "middleware.unauthenticated_denied",
          correlation_id: correlationId,
          path: pathname,
        },
        "auth.unauthenticated_denied",
      );
      return denyUnauthenticated(req, pathname, search ?? "");
    }
    const res = NextResponse.next({ request: { headers: reqHeaders } });
    ensureCsrfCookie(req, res);
    return res;
  }

  // 1b. Opaque-token detection (dashboard#357).
  //
  // Auth.js stores account.access_token at sign-in and never refreshes it.
  // Users who signed in before EnsureJWTAccessToken was applied to the
  // gibson-dashboard Zitadel OIDC app hold opaque (non-JWT) bearer tokens.
  // Envoy's jwt_authn filter rejects those with "Jwt is not in the form of
  // Header.Payload.Signature", causing every userClient RPC to fail.
  //
  // A valid JWT has exactly 3 dot-separated segments. Anything else is
  // treated as stale/opaque and the user is bounced to sign-in so Auth.js
  // mints a fresh session with a proper JWT access token.
  //
  // This check runs for ALL authenticated requests (protected and otherwise)
  // so that stale-token holders are redirected even before they reach
  // /dashboard and trigger an RPC.
  if (session.accessToken && session.accessToken.split('.').length !== 3) {
    logger.warn(
      {
        scope: "middleware.opaque_token_detected",
        correlation_id: correlationId,
        token_length: session.accessToken.length,
      },
      "auth.opaque_token_redirect",
    );
    const signInUrl = new URL("/api/auth/signin", req.nextUrl.origin);
    signInUrl.searchParams.set("callbackUrl", pathname + (search || ""));
    return NextResponse.redirect(signInUrl);
  }

  // 2. Authenticated requests that need no tenant (public pages viewed while
  //    signed in, plus the tenant-exempt onboarding endpoints), let through.
  //    The tenant/membership gate below now covers `/api/**` as well as
  //    `/dashboard`; it used to cover `/dashboard` only, so an authenticated
  //    user with no membership or a stale active-tenant cookie reached every
  //    API route with the middleware having checked neither.
  if (!requiresTenant(pathname)) {
    const res = NextResponse.next({ request: { headers: reqHeaders } });
    ensureCsrfCookie(req, res);
    return res;
  }

  // API callers get JSON, never a 302 into an HTML page. `apiRejection` builds
  // the machine-readable equivalent of each redirect below.
  const wantsJson = isApiPath(pathname);
  const apiRejection = (reason: string, status: number): NextResponse =>
    NextResponse.json({ error: "forbidden", reason }, { status });

  // 3. Resolve memberships up front so we can distinguish absent-cookie
  //    from stale-cookie precisely.
  let memberships: Awaited<ReturnType<typeof getMyMemberships>>;
  try {
    memberships = await getMyMemberships();
  } catch (err) {
    if (err instanceof MembershipResolutionError) {
      const loginErrorReason = membershipReasonToLoginErrorReason(err.reason);
      // Log the underlying ConnectRPC code alongside the user-facing
      // bucket so log review can pin a misclassification (e.g. a
      // permission_denied surfacing as daemon_unavailable would
      // re-create the dashboard#45 bug).
      logger.warn(
        {
          scope: "middleware.membership_resolution",
          membership_reason: err.reason,
          login_error_reason: loginErrorReason,
          connect_code: err.connectCode,
          correlation_id: correlationId,
        },
        "auth.login_error",
      );
      if (wantsJson) return apiRejection(loginErrorReason, 503);
      const url = new URL("/login/error", req.nextUrl.origin);
      url.searchParams.set("reason", loginErrorReason);
      return NextResponse.redirect(url);
    }
    logger.warn(
      {
        scope: "middleware.membership_resolution",
        membership_reason: "unknown",
        login_error_reason: "unknown",
        correlation_id: correlationId,
      },
      "auth.login_error",
    );
    if (wantsJson) return apiRejection("unknown", 503);
    const url = new URL("/login/error", req.nextUrl.origin);
    url.searchParams.set("reason", "unknown");
    return NextResponse.redirect(url);
  }

  // 4. Zero memberships → onboarding (NOT federated-signout).
  if (memberships.length === 0) {
    if (wantsJson) return apiRejection("no_membership", 403);
    return NextResponse.redirect(new URL("/onboarding", req.nextUrl.origin));
  }

  // 5. Check the active-tenant cookie state.
  const raw = await readRawActiveTenant();
  const returnTo = pathname + (search || "");

  if (raw.status === "absent" || raw.status === "invalid") {
    if (wantsJson) {
      const res = apiRejection(
        raw.status === "invalid" ? "tenant_cookie_invalid" : "no_active_tenant",
        403,
      );
      if (raw.status === "invalid") res.cookies.delete(ACTIVE_TENANT_COOKIE_NAME);
      return res;
    }
    const url = new URL("/select-tenant", req.nextUrl.origin);
    url.searchParams.set("return_to", returnTo);
    const res = NextResponse.redirect(url);
    if (raw.status === "invalid") {
      // Tampered/stale-secret cookie, drop it so the next request is clean.
      res.cookies.delete(ACTIVE_TENANT_COOKIE_NAME);
    }
    return res;
  }

  // 6. Cookie present + signature ok → verify membership is still current.
  const isMember = memberships.some((m) => m.tenantId === raw.tenantId);
  if (!isMember) {
    if (wantsJson) {
      const res = apiRejection("membership_revoked", 403);
      res.cookies.delete(ACTIVE_TENANT_COOKIE_NAME);
      return res;
    }
    const url = new URL("/select-tenant", req.nextUrl.origin);
    url.searchParams.set("return_to", returnTo);
    const res = NextResponse.redirect(url);
    res.cookies.delete(ACTIVE_TENANT_COOKIE_NAME);
    return res;
  }

  // 7. Healthy state, let the route render. Seed the CSRF double-submit cookie
  //    here so dashboard pages (and the mission-mutation routes they call via
  //    apiFetch) have a token to echo — the seeder used to live in the removed
  //    api proxy (dashboard#862).
  const res = NextResponse.next();
  ensureCsrfCookie(req, res);
  return res;
});

export const config = {
  matcher: [
    /*
     * Run on all paths except:
     *   - _next/static , bundled JS / CSS chunks
     *   - _next/image  , Next.js image optimiser
     *   - favicon.ico  , browser favicon
     *   - api/auth     , Auth.js OIDC callbacks
     *   - api/health   , Kubernetes probes
     *   - api/signup   , signup polling endpoint; opaque-capability protected
     *   - login/error  , deterministic error page for auth failures (public)
     *   - signup       , signup page (must stay public)
     *   - select-tenant, tenant picker (auth required, but tenant deliberately
     *                     absent here)
     *   - onboarding   , zero-membership state (auth required, no tenant)
     *
     * NOTE: /login itself is NOT excluded from the matcher. The middleware runs
     * on /login to intercept Auth.js ?error= redirects (e.g. ?error=Callback
     * from a failing jwt callback) and reroute them to /login/error. When there
     * is no ?error= param the middleware falls through immediately via step 1.
     */
    "/((?!_next/static|_next/image|favicon\\.ico|api/auth|api/health|api/signup|login/error|signup$|signup/|select-tenant$|select-tenant/|onboarding$|onboarding/).+)",
    // The pattern above ends in `.+`, which requires ≥1 char after the leading
    // slash, so it never matches the root path "/". The host split (deploy#630
    // S11) MUST run on "/", on the product host app.<domain> the landing page
    // must redirect to /dashboard rather than render. Match it explicitly.
    "/",
  ],
};
