"use server";

/**
 * provideEmailAction
 *
 * Server Action for the missing-email flow (GitHub private-email case).
 *
 * GitHub users with private email settings return no email from the OAuth
 * callback. When Better Auth creates a user with no email (or an empty
 * string), the callback route detects this and redirects to
 * `/signin/provide-email?token=<nonce>`. This action is called by that page
 * to:
 *   1. Validate the HMAC-signed nonce (15-minute expiry, BETTER_AUTH_SECRET).
 *   2. Rate-limit by IP to prevent abuse.
 *   3. Update the user row to set the email + emailVerified=false.
 *   4. Trigger a verification email via Better Auth's sendVerificationEmail.
 *   5. Redirect the browser to /verify-email?email=<email>.
 *
 * Nonce payload (JSON, HMAC-signed, base64url-encoded):
 *   { userId: string; displayName: string; exp: number }
 *
 * The nonce is generated by the GitHub callback route when it detects a
 * missing email after auth.handler processes the callback.
 */

import { headers } from "next/headers";
import type { NextRequest } from "next/server";
import { z } from "zod";

import { auth } from "@/src/lib/auth-server";
import { checkRateLimit } from "@/src/lib/rate-limiter";
import { emitAuthAudit } from "@/src/lib/audit/auth";
import { verifyProvideEmailNonce } from "@/src/lib/auth/provide-email-nonce";
import { recordDebugError } from "@/src/lib/debug";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type ProvideEmailResult =
  | { ok: true; email: string }
  | {
      ok: false;
      code:
        | "INVALID_TOKEN"
        | "TOKEN_EXPIRED"
        | "INVALID_EMAIL"
        | "EMAIL_TAKEN"
        | "RATE_LIMITED"
        | "PROVIDER_ERROR";
      message: string;
    };

// Nonce helpers moved to @/src/lib/auth/provide-email-nonce — Server Action
// files (`"use server"`) may only export async functions.

// ---------------------------------------------------------------------------
// Rate limit config
// ---------------------------------------------------------------------------

const PROVIDE_EMAIL_RATE_LIMIT = {
  maxRequests: 10,
  windowSeconds: 3600,
  algorithm: "fixed_window" as const,
  message: "Too many requests. Please try again later.",
};

// ---------------------------------------------------------------------------
// Input schema
// ---------------------------------------------------------------------------

const inputSchema = z.object({
  token: z.string().min(1),
  email: z.string().email("Please enter a valid email address"),
});

// ---------------------------------------------------------------------------
// Server Action
// ---------------------------------------------------------------------------

export async function provideEmailAction(input: {
  token: string;
  email: string;
}): Promise<ProvideEmailResult> {
  // ── Validate input ────────────────────────────────────────────────────────
  const parsed = inputSchema.safeParse(input);
  if (!parsed.success) {
    return {
      ok: false,
      code: "INVALID_EMAIL",
      message: parsed.error.issues[0]?.message ?? "Invalid input",
    };
  }
  const { token, email } = parsed.data;

  // ── Verify nonce ──────────────────────────────────────────────────────────
  const nonceResult = verifyProvideEmailNonce(token);
  if (!nonceResult.ok) {
    return {
      ok: false,
      code: nonceResult.code,
      message:
        nonceResult.code === "TOKEN_EXPIRED"
          ? "This link has expired. Please sign in again to get a new one."
          : "Invalid or tampered link. Please sign in again.",
    };
  }
  const { userId } = nonceResult.payload;

  // ── Rate limit ─────────────────────────────────────────────────────────────
  const reqHeaders = await headers();
  const fakeReq = { headers: reqHeaders } as unknown as NextRequest;
  const rl = await checkRateLimit(fakeReq, "auth:provide-email", PROVIDE_EMAIL_RATE_LIMIT);
  if (!rl.allowed) {
    return {
      ok: false,
      code: "RATE_LIMITED",
      message: PROVIDE_EMAIL_RATE_LIMIT.message,
    };
  }

  // ── Update user email ─────────────────────────────────────────────────────
  // Use Better Auth's admin API to update the user's email. The admin plugin's
  // setUserEmail / updateUser handles the DB write cleanly.
  try {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const api = auth.api as unknown as Record<string, any>;
    if (typeof api.updateUser !== "function") {
      throw new Error("updateUser endpoint not available");
    }
    await api.updateUser({
      body: { userId, email },
      headers: reqHeaders,
    });

    // Trigger email verification so the user must confirm ownership of the
    // supplied address before they can access the dashboard.
    if (typeof api.sendVerificationEmail === "function") {
      await api.sendVerificationEmail({
        body: { email },
        headers: reqHeaders,
      }).catch((err: unknown) => {
        // Non-fatal — the user can request a resend from /verify-email.
        console.error("[provide-email] sendVerificationEmail failed:", err);
      });
    }

    emitAuthAudit({
      action: "signin_social_completed",
      outcome: "ok",
      userId,
      reason: "provide_email",
    });

    return { ok: true, email };
  } catch (err) {
    const e = err instanceof Error ? err : new Error(String(err));

    // Better Auth returns an error when the email is already registered.
    if (/already.*exist|duplicate|unique/i.test(e.message)) {
      return {
        ok: false,
        code: "EMAIL_TAKEN",
        message:
          "An account with this email address already exists. Please sign in with that account.",
      };
    }

    recordDebugError({
      ts: new Date().toISOString(),
      route: "action:provideEmail",
      method: "ACTION",
      status: 500,
      message: e.message,
    });
    emitAuthAudit({
      action: "signin_social_failed",
      outcome: "failed",
      userId,
      reason: "provide_email_failed",
      errorMessage: e.message,
    });

    return {
      ok: false,
      code: "PROVIDER_ERROR",
      message: "Unable to update your account. Please try again.",
    };
  }
}
